layout_spectrum: 0.07856406713835895
typography_spectrum: 0.5192931497003883
color:
  brandStrength: 0.7682028149720281
  lightness: 0.5810902009252459
  saturation: 0.17758896481245756
  rhythmicContrast: 0.9594928966835141
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
name: kenya
